name: Lint Python with Wemake

on:
  pull_request:
    paths:
    - '**.py'

jobs:
  wemake:
    name: wemake-python-styleguide
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-setup@v1
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.15.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
